site_name: MILO

nav: #Navegação de páginas
  - Home: index.md
  - Manual de Usuário:
    - manual_usuario/index.md
    - Vendas e Rotas:
      - manual_usuario/vendas.md
      - manual_usuario/rotas.md
    - Estoque e Produtos: 
      - Cadastrando Produtos: manual_usuario/estoques.md
      - Gerenciando Estoque: manual_usuario/gerenciando-estoque.md
      - Fornecedores: manual_usuario/fornecedores.md
    - Relatórios e Controle:
      - manual_usuario/relatorios.md
      - manual_usuario/alertas.md
    - Conta e segurança:
       - Redefinindo a senha: manual_usuario/segurança.md
       - Perfil de Usuário: manual_usuario/perfil.md


  - Dúvidas Frequentes: duvidas-frequentes.md


theme:
  name: material
  palette:
  # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Modo noturno
  # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Modo claro    
  logo: img/logo.png 
  favicon: img/favicon.png
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate #pode conflitar com navigation.indexes ((checar))
    - navigation.top
    - navigation.path
#   - navigation.footer

extra_css:
  - stylesheets/extra.css 

markdown_extensions:
  - pymdownx.tasklist # Lista de tarefas
  - pymdownx.emoji # Emojis
  - pymdownx.mark # Marcação de texto
  - pymdownx.superfences # Blocos de código
  - toc: # Tabela de conteúdo à direita
      title: Índice
  - attr_list # Grids
  - md_in_html #^
  - admonition
  - pymdownx.details

plugins:
  - offline
  - search

extra:
  generator: false
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Essa página foi útil?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Essa página foi útil
          data: 1
          note: >-
            Obrigado pelo feedback!
        - icon: material/emoticon-sad-outline
          name: Essa página poderia melhorar
          data: 0
          note: >- 
            Obrigado pelo feedback!

copyright: SENAI Alagoas © 2025. Todos os direitos reservados.